# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
          anonymous: ~
          form_login:
                login_path: home
                check_path: login
                default_target_path: home
                provider: our_db_provider
          logout:
                path: /logout
                target: /home
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/add_order, roles: IS_AUTHENTICATED_FULLY }
